title: "Jeremy Côté"
author: "Jeremy"
description: "Mathematical and scientific thinking for the curious."
permalink: /:title/
lang: "en"

dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
dark_theme: false            # use the dark mode as default
show_footer: false           # show the "previous" and "next" links at the end of each post
hide_title: false            # don't show the site title in the header
style: minimal             # use a simpler style inspired by the minima theme
cvstyle: davewhipp
markdown: kramdown

navigation:                  # site navigation in the header
  - about.md
  - archive.md
  - cv.md
  - feed.xml

icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
   #rss: "/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-seo-tag

future: false
show_drafts: false
paginate: 4

text:
  pagination:
    newer: 'To the present'
    older: 'To the past'
